import { sql } from "drizzle-orm";
import { order, orderUserDetail } from "../../db";

export const derivedCurrency = sql<string>`CASE 
  WHEN ${order.currency} IS NOT NULL THEN ${order.currency}
  WHEN  LOWER(${orderUserDetail.country}) IN ('us','usa','united states','united states of america','united states of america (the)')
   THEN 'USD'
  WHEN LOWER(${orderUserDetail.country}) IN ('gh','ghana')
   THEN 'GHS'  
   WHEN LOWER(${orderUserDetail.country}) IN ('eur','de','fr','it','es','nl','pt','at','be','ie','gr')
   THEN 'EUR'
  WHEN ${orderUserDetail.country} = 'United Kingdom' 
  THEN 'GBP'
  ELSE 'Unknown'
END`;

export const europeanCountries = [
  "DE",
  "NO",
  "FR",
  "IT",
  "ES",
  "NL",
  "EU",
  "Albania",
  "Andorra",
  "Austria",
  "Belarus",
  "Belgium",
  "Bosnia and Herzegovina",
  "Bulgaria",
  "Croatia",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Estonia",
  "Finland",
  "France",
  "Germany",
  "Greece",
  "Hungary",
  "Iceland",
  "Ireland",
  "Italy",
  "Kosovo",
  "Latvia",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Malta",
  "Moldova",
  "Monaco",
  "Montenegro",
  "Netherlands",
  "North Macedonia",
  "Norway",
  "Poland",
  "Portugal",
  "Romania",
  "Russia",
  "San Marino",
  "Serbia",
  "Slovakia",
  "Slovenia",
  "Spain",
  "Sweden",
  "Switzerland",
  "Turkey",
  "Ukraine",
  "United Kingdom",
  "Vatican City",
];

const europeanCountries_with_codes = [
  { country: "Albania", code: "AL" },
  { country: "Andorra", code: "AD" },
  { country: "Austria", code: "AT" },
  { country: "Belarus", code: "BY" },
  { country: "Belgium", code: "BE" },
  { country: "Bosnia and Herzegovina", code: "BA" },
  { country: "Bulgaria", code: "BG" },
  { country: "Croatia", code: "HR" },
  { country: "Cyprus", code: "CY" },
  { country: "Czech Republic", code: "CZ" },
  { country: "Denmark", code: "DK" },
  { country: "Estonia", code: "EE" },
  { country: "Finland", code: "FI" },
  { country: "France", code: "FR" },
  { country: "Germany", code: "DE" },
  { country: "Greece", code: "GR" },
  { country: "Hungary", code: "HU" },
  { country: "Iceland", code: "IS" },
  { country: "Ireland", code: "IE" },
  { country: "Italy", code: "IT" },
  { country: "Kosovo", code: "XK" }, // unofficial but commonly used
  { country: "Latvia", code: "LV" },
  { country: "Liechtenstein", code: "LI" },
  { country: "Lithuania", code: "LT" },
  { country: "Luxembourg", code: "LU" },
  { country: "Malta", code: "MT" },
  { country: "Moldova", code: "MD" },
  { country: "Monaco", code: "MC" },
  { country: "Montenegro", code: "ME" },
  { country: "Netherlands", code: "NL" },
  { country: "North Macedonia", code: "MK" },
  { country: "Norway", code: "NO" },
  { country: "Poland", code: "PL" },
  { country: "Portugal", code: "PT" },
  { country: "Romania", code: "RO" },
  { country: "Russia", code: "RU" },
  { country: "San Marino", code: "SM" },
  { country: "Serbia", code: "RS" },
  { country: "Slovakia", code: "SK" },
  { country: "Slovenia", code: "SI" },
  { country: "Spain", code: "ES" },
  { country: "Sweden", code: "SE" },
  { country: "Switzerland", code: "CH" },
  { country: "Turkey", code: "TR" },
  { country: "Ukraine", code: "UA" },
  { country: "United Kingdom", code: "GB" },
  { country: "Vatican City", code: "VA" },
];
